services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB:
    ports:
      - "5433:5432"   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ph"]
      interval: 5s
      timeout: 5s
      retries: 10
